### ISSUE TITLE
Incorrect number of TypeVariable instances created during cycle

### ISSUE THREAD

**Issue by Florent-H** [samuelduchesne/pyTrnsysType#14]
In the method **_resolve_cycles**, when creating mutiple similar parameters, inputs, or outputs (_i.e._ TypeVariables) based on the value of a parameter (_e.g._ "Number_of_Outlet_Ports" for the Type647), not all TypeVariables are created.

Using the example of Type647 (_Fluid Diverting Valve w/Up to 100 Outlets_), there is only one instance of the output "Outlet_Flowrate" even though the cycling parameter "Number_of_Outlet_Ports" is set to 3. On the other hand, 3 instances of "Outlet_Temperature" are created, as expected.

[![pyTrnsysType - Issue](https://user-images.githubusercontent.com/37128576/60930460-a25e1100-a283-11e9-99ae-efbd494d5149.PNG)](url)

**Comment by samuelduchesne** [comment]
Will investigate 🕵️‍♂️

**Comment by samuelduchesne** [comment]
Good catch! This has been fixed with #15
