### ISSUE TITLE
Equation.from_symbolic_expression possibly considers the predicates LT, GT, etc. to be symbolic variables

### ISSUE THREAD

**Issue by Florent-H** [samuelduchesne/pyTrnsysType#22]
Consider the following implementation of the method _from_symbolic_expression_ from the _Equation_ class:

```
# names of variables in equation
build_loop = "QBuildingLoop"
cap = "capacity"
load = "load"

exp_build_loop = "LT(l, c)*l + GE(l, c)*c"
eq_build_loop = Equation.from_symbolic_expression(build_loop, exp_build_loop, *(load, capacity))
```

The repr output for **eq_build_loop** becomes

`QBuildingLoop = capacity**2 + load*GE(capacity, load)`.

I have tried to figure out exactly why this is outputted, but my best guess is that _from_symbolic_expression_ is interpreting "LT" to be a symbolic variable. Further investigation is needed.

**Comment by samuelduchesne** [comment]
@Florent-H, the sympy module documentation (which is used to parse expressions) shows that the "lower than", "greater than", etc. operators are written with a capital letter followed by a lower-case.

by changing the expressions above to `exp_build_loop = "Lt(l, c)*l + Ge(l, c)*c"` you get the expected result: `QBuildingLoop = capacity*(capacity < load) + load*(capacity >= load)`
